// Generated — kode saham → nama perusahaan. Sumber: daftar kurasi + data FCA.
export const COMPANY_NAMES: Record<string, string> = {
  "BMHS": "Bundamedik",
  "BBCA": "Bank Central Asia",
  "BMRI": "Bank Mandiri",
  "BBRI": "Bank Rakyat Indonesia",
  "BBNI": "Bank Negara Indonesia",
  "BRIS": "Bank Syariah Indonesia",
  "BTPN": "Bank BTPN",
  "ARTO": "Bank Jago",
  "NISP": "Bank OCBC NISP",
  "PNBN": "Bank Pan Indonesia",
  "BJBR": "Bank BJB",
  "BJTM": "Bank Jatim",
  "BDMN": "Bank Danamon",
  "MEGA": "Bank Mega",
  "BBTN": "Bank Tabungan Negara",
  "ADRO": "Adaro Energy",
  "PTBA": "Bukit Asam",
  "ITMG": "Indo Tambangraya Megah",
  "UNTR": "United Tractors",
  "INCO": "Vale Indonesia",
  "ANTM": "Aneka Tambang",
  "MDKA": "Merdeka Copper Gold",
  "BRMS": "Bumi Resources Minerals",
  "MEDC": "Medco Energi",
  "PGAS": "Perusahaan Gas Negara",
  "ELSA": "Elnusa",
  "AKRA": "AKR Corporindo",
  "BREN": "Barito Renewables Energy",
  "AMMN": "Amman Mineral Internasional",
  "DSSA": "Dian Swastatika Sentosa",
  "BRPT": "Barito Pacific",
  "TPIA": "Chandra Asri Pacific",
  "CPIN": "Charoen Pokphand Indonesia",
  "JPFA": "Japfa Comfeed",
  "SIMP": "Salim Ivomas Pratama",
  "TLKM": "Telkom Indonesia",
  "ISAT": "Indosat",
  "EXCL": "XL Axiata",
  "TOWR": "Sarana Menara Nusantara",
  "MTEL": "Dayamitra Telekomunikasi",
  "TBIG": "Tower Bersama Infrastructure",
  "GOTO": "GoTo Gojek Tokopedia",
  "BUKA": "Bukalapak",
  "EMTK": "Elang Mahkota Teknologi",
  "MNCN": "Media Nusantara Citra",
  "SCMA": "Surya Citra Media",
  "MLPT": "Multipolar Technology",
  "ICBP": "Indofood CBP Sukses Makmur",
  "INDF": "Indofood Sukses Makmur",
  "MYOR": "Mayora Indah",
  "ULTJ": "Ultrajaya Milk",
  "CMRY": "Cisarua Mountain Dairy",
  "KLBF": "Kalbe Farma",
  "SIDO": "Industri Jamu dan Farmasi Sido Muncul",
  "UNVR": "Unilever Indonesia",
  "HMSP": "HM Sampoerna",
  "GGRM": "Gudang Garam",
  "AMRT": "Sumber Alfaria Trijaya",
  "ACES": "Ace Hardware Indonesia",
  "MAPI": "Mitra Adiperkasa",
  "ERAA": "Erajaya Swasembada",
  "LPPF": "Matahari Department Store",
  "RALS": "Ramayana Lestari Sentosa",
  "AALI": "Astra Agro Lestari",
  "LSIP": "PP London Sumatra Indonesia",
  "SMAR": "Sinar Mas Agro Resources",
  "ANJT": "Austindo Nusantara Jaya",
  "BSDE": "Bumi Serpong Damai",
  "CTRA": "Ciputra Development",
  "PWON": "Pakuwon Jati",
  "SMRA": "Summarecon Agung",
  "ASRI": "Alam Sutera Realty",
  "JSMR": "Jasa Marga",
  "WIKA": "Wijaya Karya",
  "PTPP": "PP",
  "ADHI": "Adhi Karya",
  "SMGR": "Semen Indonesia",
  "INTP": "Indocement Tunggal Prakarsa",
  "ASII": "Astra International",
  "GIAA": "Garuda Indonesia",
  "MIKA": "Mitra Keluarga",
  "SILO": "Siloam International Hospitals",
  "HEAL": "Medikaloka Hermina",
  "ISSP": "Steel Pipe Industry of Indonesia",
  "KRAS": "Krakatau Steel",
  "INKP": "Indah Kiat Pulp & Paper",
  "TKIM": "Pabrik Kertas Tjiwi Kimia",
  "FUTR": "PT Futura Energi Global Tbk",
  "FILM": "PT MD Entertainment Tbk",
  "IMPC": "PT Impack Pratama Industri Tbk",
  "MKPI": "Metropolitan Kentjana Tbk",
  "DATA": "PT Remala Abadi Tbk",
  "BKSL": "Sentul City Tbk",
  "EURO": "PT Estee Gold Feet Tbk",
  "BEEF": "PT Estika Tata Tiara Tbk.",
  "OASA": "PT Maharaksa Biru Energi Tbk",
  "DAAZ": "PT Daaz Bara Lestari Tbk",
  "VISI": "PT Satu Visi Putra Tbk.",
  "FUJI": "PT Fuji Finance Indonesia Tbk.",
  "WIFI": "PT Solusi Sinergi Digital Tbk",
  "PADI": "Minna Padi Investama Sekuritas Tbk",
  "DMMX": "PT Digital Mediatama Maxima Tbk",
  "PKPK": "Paragon Karya Perkasa Tbk",
  "AGII": "PT Samator Indo Gas Tbk",
  "BINA": "PT Bank Ina Perdana Tbk.",
  "CUAN": "PT Petrindo Jaya Kreasi Tbk",
  "AYAM": "PT Janu Putra Sejahtera Tbk.",
  "ARCI": "PT Archi Indonesia Tbk",
  "DWGL": "PT Dwi Guna Laksana Tbk",
  "KBLV": "First Media Tbk",
  "JECC": "Jembo Cable Company Tbk",
  "HALO": "PT Haloni Jane Tbk",
  "BMAS": "PT Bank Maspion Indonesia Tbk.",
  "BAUT": "PT Mitra Angkasa Sejahtera Tbk",
  "HILL": "PT Hillcon Tbk",
  "LUCY": "PT Lima Dua Lima Tiga Tbk",
  "SWAT": "PT Sriwahana Adityakarta Tbk.",
  "PTSP": "Pioneerindo Gourmet International Tbk",
  "TARA": "PT Agung Semesta Sejahtera Tbk",
  "MIRA": "Mitra International Resources Tbk",
  "MEJA": "PT Harta Djaya Karya Tbk",
  "ESTA": "PT Esta Multi Usaha Tbk.",
  "DOOH": "PT Era Media Sejahtera Tbk",
  "NTBK": "PT Nusatama Berkah Tbk",
  "STRK": "PT Lovina Beach Brewery Tbk.",
  "PDES": "Destinasi Tirta Nusantara Tbk",
  "PURA": "PT Putra Rajawali Kencana Tbk.",
  "RONY": "PT Aracord Nusantara Group Tbk",
  "NATO": "PT Surya Permata Andalan Tbk",
  "PPRO": "PT PP Properti Tbk.",
  "SAFE": "Steady Safe Tbk",
  "BCAP": "MNC Kapital Indonesia Tbk",
  "AIMS": "PT Artha Mahiya Investama Tbk",
  "MPIX": "PT Mitra Pedagang Indonesia Tbk.",
  "OLIV": "PT Oscar Mitra Sukses Sejahtera Tbk",
  "TRST": "Trias Sentosa Tbk",
  "POLA": "PT Pool Advista Finance Tbk.",
  "VIVA": "PT Visi Media Asia Tbk",
  "BOLT": "PT Garuda Metalindo Tbk.",
  "DCII": "PT DCI Indonesia Tbk",
  "FMII": "Fortune Mate Indonesia Tbk",
  "CBUT": "PT Citra Borneo Utama Tbk",
  "BAYU": "Bayu Buana Tbk",
  "RELI": "Reliance Sekuritas Indonesia Tbk",
  "ALII": "PT Ancara Logistics Indonesia Tbk",
  "EPMT": "Enseval Putera Megatrading Tbk",
  "JAWA": "Jaya Agra Wattie Tbk",
  "WOWS": "PT Ginting Jaya Energi Tbk",
  "MSIE": "PT Multisarana Intan Eduka Tbk",
  "TIRA": "Tira Austenite Tbk",
  "PIPA": "PT Multi Makmur Lemindo Tbk.",
  "SCCO": "PT Supreme Cable Manufacturing & Commerce Tbk",
  "YELO": "PT Yelooo Integra Datanet Tbk.",
  "SQMI": "Wilton Makmur Indonesia Tbk",
  "TOTO": "Surya Toto Indonesia Tbk",
  "KDSI": "Kedawung Setia Industrial Tbk",
  "ASHA": "PT Cilacap Samudera Fishing Industry Tbk",
  "AYLS": "PT Agro Yasa Lestari Tbk",
  "INDS": "Indospring Tbk",
  "PPGL": "PT Prima Globalindo Logistik Tbk.",
  "ABDA": "Asuransi Bina Dana Arta Tbk",
  "ASLI": "PT Asri Karya Lestari Tbk.",
  "NIRO": "City Retail Developments Tbk",
  "BCIC": "PT Bank JTrust Indonesia Tbk.",
  "BPII": "PT Batavia Prosperindo Internasional Tbk.",
  "HELI": "PT Jaya Trishindo Tbk",
  "IFSH": "PT Ifishdeco Tbk.",
  "RLCO": "PT Abadi Lestari Indonesia Tbk",
  "POOL": "Pool Advista Indonesia Tbk",
  "LEAD": "PT Logindo Samudramakmur Tbk.",
  "KBAG": "PT Karya Bersama Anugerah Tbk",
  "JATI": "PT Informasi Teknologi Indonesia Tbk.",
  "JAST": "PT Jasnita Telekomindo Tbk.",
  "IPTV": "PT MNC Vision Networks Tbk.",
  "INPP": "Indonesian Paradise Property Tbk",
  "GMFI": "PT Garuda Maintenance Facility Aero Asia Tbk.",
  "MINA": "PT Sanurhasta Mitra Tbk.",
  "JGLE": "PT Graha Andrasentra Propertindo Tbk.",
  "IBOS": "PT Indo Boga Sukses Tbk",
  "UNSP": "Bakrie Sumatera Plantations Tbk",
  "IPAC": "PT Era Graharealty Tbk",
  "INPS": "PT Indah Prakasa Sentosa Tbk.",
  "KRYA": "PT Bangun Karya Perkasa Jaya Tbk",
  "BRRC": "PT Raja Roti Cemerlang Tbk",
  "BHIT": "PT MNC Asia Holding Tbk",
  "PSKT": "PT Red Planet Indonesia Tbk",
  "WBSA": "PT BSA Logistics Indonesia Tbk",
  "RGAS": "PT Kian Santang Muliatama Tbk.",
  "SPRE": "PT Soraya Berjaya Indonesia Tbk",
  "ROCK": "PT Rockfields Properti Indonesia Tbk.",
  "LIFE": "PT MSIG Life Insurance Indonesia Tbk.",
  "DKHH": "PT Cipta Sarana Medika Tbk",
  "SMDM": "Suryamas Dutamakmur Tbk",
  "OMRE": "Indonesia Prima Property Tbk",
  "PLIN": "Plaza Indonesia Realty Tbk",
  "YPAS": "Yanaprima Hastapersada Tbk",
  "JIHD": "Jakarta International Hotels & Development Tbk",
  "HADE": "PT Himalaya Energi Perkasa Tbk",
  "STAR": "PT Buana Artha Anugerah Tbk.",
  "POLI": "PT Pollux Hotels Group Tbk",
  "LAJU": "PT Jasa Berdikari Logistics Tbk",
  "HBAT": "PT Minahasa Membangun Hebat Tbk",
  "BKDP": "Bukit Darmo Property Tbk",
  "TAMU": "PT Pelayaran Tamarin Samudra Tbk.",
  "RBMS": "Ristia Bintang Mahkotasejati Tbk",
  "ADES": "Akasha Wira International Tbk  Tbk",
  "BSBK": "PT Wulandari Bangun Laksana Tbk",
  "CHIP": "PT Pelita Teknologi Global Tbk",
  "WSKT": "PT Waskita Karya (Persero) Tbk",
  "PBRX": "Pan Brothers Tbk",
  "GDYR": "Goodyear Indonesia Tbk",
  "ANDI": "PT Andira Agro Tbk",
  "BLUE": "PT Berkah Prima Perkasa Tbk",
  "KOCI": "PT Kokoh Exa Nusantara",
  "LAND": "PT Trimitra Propertindo Tbk.",
  "NZIA": "PT Nusantara Almazia, Tbk.",
  "HRME": "PT Menteng Heritage Realty Tbk.",
  "AGAR": "PT Asia Sejahtera Mina Tbk",
  "IKAI": "Intikeramik Alamasri Industri Tbk",
  "BEKS": "PT Bank Pembangunan Daerah Banten Tbk.",
  "MLIA": "Mulia Industrindo Tbk",
  "SHIP": "PT Sillo Maritime Perdana Tbk",
  "UNIQ": "PT Ulima Nitra Tbk",
  "KKES": "PT Kusuma Kemindo Sentosa Tbk",
  "SOHO": "PT Soho Global Health Tbk",
  "LPGI": "Lippo General Insurance Tbk",
  "PGLI": "Pembangunan Graha Lestari Indah Tbk",
  "GDST": "Gunawan Dianjaya Steel Tbk",
  "UANG": "PT Pakuan Tbk",
  "COCO": "PT Wahana Interfood Nusantara Tbk.",
  "RATU": "PT Raharja Energi Cepu Tbk",
  "IKAN": "PT Era Mandiri Cemerlang Tbk",
  "MASB": "PT Bank Multiarta Sentosa Tbk",
  "TRON": "PT Teknologi Karya Digital Nusa Tbk.",
  "KLIN": "PT Klinko Karya Imaji Tbk",
  "PLAN": "PT Planet Properindo Jaya Tbk",
  "LCKM": "PT LCK Global Kedaton Tbk",
  "BMSR": "Bintang Mitra Semestaraya Tbk",
  "IIKP": "Inti Agri Resources Tbk",
  "FASW": "Fajar Surya Wisesa Tbk",
  "RANC": "Supra Boga Lestari Tbk",
  "KMTR": "PT Kirana Megatara Tbk.",
  "CTBN": "Citra Tubindo Tbk",
  "SSTM": "Sunson Textile Manufacturer Tbk",
  "CITY": "PT Natura City Developments Tbk.",
  "ASBI": "Asuransi Bintang Tbk",
  "ABBA": "Mahaka Media Tbk",
  "TOYS": "PT Sunindo Adipersada Tbk.",
  "DUCK": "PT Jaya Bersama Indo Tbk.",
  "POSA": "PT Bliss Properti Indonesia Tbk.",
  "PTMR": "PT Master Print Tbk",
  "ZATA": "PT Bersama Zatta Jaya Tbk",
  "PEGE": "PT Panca Global Kapital Tbk.",
  "PBSA": "PT Paramita Bangun Sarana Tbk",
  "COAL": "PT Black Diamond Resources Tbk",
  "SRSN": "Indo Acidatama Tbk",
  "LINK": "PT Link Net Tbk.",
  "GMTD": "Gowa Makassar Tourism Development Tbk",
  "NICL": "PT PAM Mineral Tbk",
  "ARTA": "Arthavest Tbk",
  "BOLA": "PT Bali Bintang Sejahtera Tbk.",
  "TIFA": "KDB Tifa Finance Tbk",
  "MAPB": "PT Map Boga Adiperkasa Tbk",
  "MDRN": "Modern Internasional Tbk",
  "ASMI": "PT Asuransi Maximus Graha Persada Tbk.",
  "PUDP": "Pudjiadi Prestige Tbk",
  "FIRE": "PT Alfa Energi Investama Tbk.",
  "DMND": "PT Diamond Food Indonesia Tbk.",
  "ARKO": "PT Arkora Hydro Tbk.",
  "SOFA": "PT Boston Furniture Industries Tbk..",
  "ENZO": "PT Morenzo Abadi Perkasa Tbk",
  "SCNP": "PT Selaras Citra Nusantara Perkasa Tbk",
  "KPIG": "MNC Land Tbk",
  "AMMS": "PT Agung Menjangan Mas Tbk",
  "IATA": "PT MNC Energy Investments Tbk",
  "SRAJ": "Sejahteraraya Anugrahjaya Tbk",
  "GGRP": "PT Gunung Raja Paksi Tbk.",
  "BLTA": "Berlian Laju Tanker Tbk",
  "DADA": "PT Diamond Citra Propertindo Tbk.",
  "COIN": "PT Indokripto Koin Semesta Tbk",
  "SDMU": "Sidomulyo Selaras Tbk",
  "SOSS": "PT Shield On Service Tbk.",
  "KARW": "Meratus Jasa Prima Tbk",
  "AGRS": "PT Bank IBK Indonesia Tbk.",
  "SHID": "Hotel Sahid Jaya Tbk",
  "ESTI": "Ever Shine Textile Industry Tbk",
  "PURI": "PT Puri Global Sukses Tbk",
  "KJEN": "PT Krida Jaringan Nusantara Tbk.",
  "TMPO": "Tempo Inti Media Tbk",
  "URBN": "PT Urban Jakarta Propertindo Tbk.",
  "GAMA": "Aksara Global Development Tbk",
  "LMAS": "Limas Indonesia Makmur Tbk",
  "SUGI": "Sugih Energy Tbk",
  "KAYU": "PT Darmi Bersaudara Tbk.",
  "CSAP": "Catur Sentosa Adiprana Tbk",
  "CSIS": "PT Cahayasakti Investindo Sukses Tbk",
  "PGUN": "PT Pradiksi Gunatama Tbk",
  "SMKM": "PT Sumber Mas Konstruksi Tbk",
  "SOTS": "PT Satria Mega Kencana Tbk.",
  "MPRO": "PT Maha Properti Indonesia Tbk.",
  "RMKE": "PT RMK Energy Tbk",
  "NSSS": "PT Nusantara Sawit Sejahtera Tbk",
  "BIPI": "PT Astrindo Nusantara Infrastruktur Tbk.",
  "WIDI": "PT Widiant Jaya Krenindo Tbk.",
  "ASRM": "Asuransi Ramayana Tbk",
  "SATU": "PT Kota Satu Properti Tbk.",
  "MYTX": "PT Asia Pacific Investama Tbk.",
  "ARMY": "PT Armidian Karyatama Tbk",
  "CENT": "PT Centratama Telekomunikasi Indonesia Tbk.",
  "FPNI": "PT Lotte Chemical Titan Tbk.",
  "HOTL": "Saraswati Griya Lestari Tbk",
  "CPRI": "PT Capri Nusa Satu Properti Tbk.",
  "MTFN": "Capitalinc Investment Tbk",
  "ALMI": "Alumindo Light Metal Industry Tbk",
  "LMSH": "Lionmesh Prima Tbk",
  "ADMR": "PT Adaro Minerals Indonesia Tbk",
  "PADA": "PT Personel Alih Daya Tbk",
  "RSGK": "PT Kedoya Adyaraya Tbk",
  "CMNP": "Citra Marga Nusaphala Persada Tbk",
  "PALM": "Provident Agro Tbk",
  "BESS": "PT Batulicin Nusantara Maritim Tbk.",
  "PMMP": "PT Panca Mitra Multiperdana Tbk.",
  "TAYS": "PT Jaya Swarasa Agung Tbk",
  "TRAM": "Trada Alam Minera Tbk.",
  "BWPT": "Eagle High Plantations Tbk",
  "NASA": "PT Andalan Perkasa Abadi Tbk",
  "KOIN": "Kokoh Inti Arebama Tbk",
  "TGRA": "PT Terregra Asia Energy",
  "UNIT": "Nusantara Inti Corpora Tbk",
  "MABA": "PT Marga Abhinaya Abadi Tbk",
  "JMAS": "PT Asuransi Jiwa Syariah Jasa Mitra Abadi Tbk",
  "TRUK": "PT Guna Timur Raya Tbk.",
  "SONA": "Sona Topas Tourism Industry Tbk",
  "TMAS": "PT Temas Tbk.",
  "BAPA": "Bekasi Asri Pemula Tbk",
  "LCGP": "PT Eureka Prima Jakarta Tbk.",
  "JSKY": "PT Sky Energy Indonesia Tbk.",
  "INTD": "Inter-Delta Tbk",
  "SAGE": "PT Saptausaha Gemilangindah Tbk",
  "RODA": "Pikko Land Development Tbk",
  "IBST": "Inti Bangun Sejahtera Tbk",
  "FIMP": "PT Fimperkasa Utama Tbk",
  "MTRA": "PT Mitra Pemuda Tbk.",
  "POLL": "PT Pollux Properties Indonesia Tbk.",
  "BIKA": "PT Binakarya Jaya Abadi Tbk.",
  "TDPM": "PT Tianrong Chemicals Industry Tbk",
  "HOPE": "PT Harapan Duta Pertiwi Tbk.",
  "DEWI": "PT Dewi Shri Farmindo Tbk",
  "TAXI": "Express Transindo Utama Tbk",
  "SINI": "PT Singaraja Putra Tbk.",
  "KING": "PT Hoffmen Cleanindo Tbk",
  "NASI": "PT Wahana Inti Makmur Tbk",
  "FOLK": "PT Multi Garam Utama Tbk.",
  "BLTZ": "PT Graha Layar Prima Tbk.",
  "ZBRA": "PT Dosni Roha Indonesia Tbk",
  "SMRU": "SMR Utama Tbk",
  "FLMC": "PT Falmaco Nonwoven Industri Tbk",
  "LFLO": "PT Imago Mulia Persada Tbk",
  "BABY": "PT Multitrend Indo Tbk.",
  "BPTR": "PT Batavia Prosperindo Trans Tbk.",
  "NINE": "PT Techno9 Indonesia Tbk",
  "BUVA": "PT Bukit Uluwatu Villa Tbk",
  "PANI": "PT Pratama Abadi Nusa Industri Tbk.",
  "YULE": "Yulie Sekuritas Indonesia Tbk",
  "SOUL": "PT Mitra Tirta Buwana Tbk",
  "IBFN": "PT Intan Baru Prana Tbk",
  "TECH": "PT Indosterling Technomedia Tbk",
  "MENN": "PT Menn Teknologi Indonesia Tbk.",
  "SURE": "PT Super Energy Tbk.",
  "BRNA": "Berlina Tbk",
  "ARGO": "Argo Pantes Tbk",
  "RISE": "PT Jaya Sukses Makmur Sentosa Tbk.",
  "TRIL": "Triwira Insanlestari Tbk",
  "SBAT": "PT Sejahtera Bintang Abadi Textile Tbk.",
  "COWL": "COWELL DEVELOPMENT Tbk",
  "ENVY": "PT Envy Technologies Indonesia Tbk",
  "PURE": "PT Trinitan Metals and Minerals Tbk",
  "ICON": "Island Concepts Indonesia Tbk",
  "INET": "PT Sinergi Inti Andalan Prima Tbk.",
  "TGUK": "PT Platinum Wahab Nusantara Tbk.",
  "PACK": "PT Abadi Nusantara Hijau Investama Tbk",
  "CBRE": "PT Cakra Buana Resources Energi Tbk",
  "KDTN": "PT Puri Sentul Permai Tbk",
  "TNCA": "PT Trimuda Nuansa Citra Tbk.",
  "BIPP": "Bhuwanatala Indah Permai Tbk",
  "INDX": "Tanah Laut Tbk",
  "BTEL": "Bakrie Telecom Tbk",
  "BATA": "Sepatu Bata Tbk",
  "RAFI": "PT Sari Kreasi Boga Tbk",
  "KREN": "PT Kresna Graha Investama Tbk.",
  "SMMT": "GOLDEN EAGLE ENERGY Tbk",
  "BSWD": "Bank of India Indonesia Tbk",
  "MFMI": "Multifiling Mitra Indonesia Tbk",
  "KIAS": "Keramika Indonesia Assosiasi Tbk",
  "GLOB": "PT Globe Kita Terang Tbk",
  "HOME": "Hotel Mandarine Regency Tbk",
  "CBMF": "PT Cahaya Bintang Medan Tbk",
  "BEBS": "PT Berkah Beton Sadaya Tbk",
  "VKTR": "PT VKTR Teknologi Mobilitas Tbk",
  "BAIK": "PT Bersama Mencapai Puncak Tbk.",
  "FAST": "PT Fast Food Indonesia Tbk",
  "MSIN": "PT MNC Digital Entertainment Tbk",
  "WINR": "PT Winner Nusantara Jaya Tbk",
  "SULI": "PT SLJ Global Tbk",
  "RMKO": "PT Royaltama Mulia Kontraktorindo Tbk.",
  "POLU": "PT Golden Flower Tbk.",
  "INCF": "PT Indo Komoditi Korpora Tbk",
  "HITS": "Humpuss Intermoda Transportasi Tbk",
  "CSMI": "PT Cipta Selera Murni Tbk.",
  "CTTH": "Citatah Tbk",
  "LMPI": "Langgeng Makmur Industri Tbk",
  "ALKA": "Alakasa Industrindo Tbk",
  "PTPS": "PT Pulau Subur Tbk.",
  "PTDU": "PT Djasa Ubersakti Tbk",
  "POLY": "Asia Pacific Fibers Tbk",
  "IPPE": "PT Indo Pureco Pratama Tbk",
  "GOLL": "PT Golden Plantation Tbk",
  "TAMA": "PT Lancartama Sejati Tbk.",
  "GRPM": "PT Graha Prima Mentari Tbk.",
  "REAL": "PT Repower Asia Indonesia Tbk.",
  "SMLE": "PT Sinergi Multi Lestarindo Tbk",
  "TEBE": "PT Dana Brata Luhur Tbk.",
  "KOTA": "PT DMS Propertindo Tbk.",
  "MPPA": "Matahari Putra Prima Tbk",
  "DKFT": "Central Omega Resources Tbk",
  "MORA": "PT Mora Telematika Indonesia Tbk",
  "KOPI": "PT Mitra Energi Persada Tbk",
  "SAPX": "PT Satria Antaran Prima Tbk.",
  "LAPD": "Leyand International Tbk",
  "FORU": "Fortune Indonesia Tbk",
  "INTA": "Intraco Penta Tbk",
  "DEAL": "PT Dewata Freightinternational Tbk.",
  "ASPI": "PT Andalan Sakti Primaindo Tbk.",
  "UDNG": "PT Agro Bahari Nusantara Tbk",
  "PNSE": "Pudjiadi & Sons Tbk",
  "AKSI": "PT Mineral Sumberdaya Mandiri Tbk",
  "FISH": "FKS Multi Agro Tbk",
  "MARI": "PT Mahaka Radio Integra Tbk.",
  "SRIL": "PT Sri Rejeki Isman Tbk",
  "MAGP": "Multi Agro Gemilang Plantation Tbk",
  "CANI": "PT Capitol Nusantara Indonesia Tbk.",
  "GTBO": "Garda Tujuh Buana Tbk",
  "ARTI": "Ratu Prabu Energi Tbk",
  "MMIX": "PT Multi Medika Internasional Tbk",
  "ELPI": "PT Pelayaran Nasional Ekalya Purnamasari Tbk",
  "IRSX": "PT Folago Global Nusantara Tbk",
  "NANO": "PT Nanotech Indonesia Global Tbk",
  "PYFA": "PT Pyridam Farma Tbk",
  "ISAP": "PT Isra Presisi Indonesia Tbk",
  "TFCO": "Tifico Fiber Indonesia Tbk",
  "BTEK": "Bumi Teknokultura Unggul Tbk",
  "TALF": "TUNAS ALFIN Tbk",
  "ESIP": "PT Sinergi Inti Plastindo Tbk.",
  "LABA": "PT Green Power Group Tbk",
  "CITA": "Cita Mineral Investindo Tbk",
  "TRIO": "Trikomsel Oke Tbk",
  "HDIT": "PT Hensel Davest Indonesia Tbk",
  "SKBM": "Sekar Bumi Tbk",
  "BKSW": "PT Bank QNB Indonesia Tbk",
  "CLAY": "PT Citra Putra Realty Tbk",
  "DUTI": "Duta Pertiwi Tbk",
  "PTIS": "Indo Straits Tbk",
  "INPC": "Bank Artha Graha Internasional Tbk",
  "LION": "Lion Metal Works Tbk",
  "ARKA": "PT Arkha Jayanti Persada Tbk.",
  "AKKU": "PT Anugerah Kagum Karya Utama Tbk",
  "SMCB": "PT Solusi Bangun Indonesia Tbk",
  "ITIC": "PT Indonesian Tobacco Tbk.",
  "SIPD": "PT Sreeya Sewu Indonesia Tbk",
  "AHAP": "Asuransi Harta Aman Pratama Tbk",
  "GPSO": "PT Geoprima Solusi Tbk",
  "SOLA": "PT Xolare RCR Energy Tbk",
  "NAYZ": "PT Hassana Boga Sejahtera Tbk",
  "PGJO": "PT Bahtera Bumi Raya Tbk",
  "BAPI": "PT Bhakti Agung Propertindo Tbk.",
  "BMBL": "PT Lavender Bina Cendikia Tbk",
  "BNBR": "Bakrie & Brothers Tbk",
  "BTON": "Betonjaya Manunggal Tbk",
  "MAXI": "PT Maxindo Karya Anugerah Tbk",
  "TRUE": "PT Triniti Dinamik Tbk",
  "SIMA": "Siwani Makmur Tbk",
  "WSBP": "PT Waskita Beton Precast Tbk.",
  "TINS": "PT Timah Tbk.",
  "JARR": "PT Jhonlin Agro Raya Tbk",
  "ELTY": "Bakrieland Development Tbk",
  "ALTO": "Tri Banyan Tirta Tbk",
  "WICO": "Wicaksana Overseas International Tbk",
  "PLAS": "Polaris Investama Tbk",
  "OCAP": "ONIX CAPITAL Tbk",
  "SCPI": "PT Organon Pharma Indonesia Tbk",
  "BOSS": "PT Borneo Olah Sarana Sukses Tbk.",
  "KBRI": "Kertas Basuki Rachmat Indonesia Tbk",
  "MGLV": "PT Panca Anugrah Wisesa Tbk",
  "WMUU": "PT Widodo Makmur Unggas Tbk",
  "MDIA": "PT Intermedia Capital Tbk.",
  "ASPR": "PT Asia Pramulia Tbk",
  "CARE": "PT Metro Healthcare Indonesia Tbk",
  "CDIA": "PT Chandra Daya Investasi Tbk",
  "GEMA": "Gema Grahasarana Tbk",
  "BELL": "PT Trisula Textile Industries Tbk",
  "NETV": "PT Net Visi Media Tbk",
  "CARS": "PT Industri dan Perdagangan Bintraco Dharma Tbk",
  "SKLT": "Sekar Laut Tbk",
  "DPUM": "PT Dua Putra Utama Makmur Tbk.",
  "MGNA": "PT Magna Investama Mandiri Tbk",
  "EPAC": "PT Megalestari Epack Sentosaraya Tbk.",
  "TRIN": "PT Perintis Triniti Properti Tbk",
  "DEFI": "Danasupra Erapacific Tbk",
  "META": "Nusantara Infrastructure Tbk",
  "DIGI": "PT Arkadia Digital Media Tbk",
  "RIMO": "PT Rimo International Lestari Tbk.",
  "ZINC": "PT Kapuas Prima Coal Tbk",
  "INRU": "Toba Pulp Lestari Tbk",
  "TIRT": "Tirta Mahakam Resources Tbk",
  "SGRO": "PT Prime Agri Resources Tbk",
  "KIOS": "PT Kioson Komersial Indonesia Tbk.",
  "KONI": "Perdana Bangun Pusaka Tbk",
  "JSPT": "Jakarta Setiabudi Internasional Tbk",
  "RICY": "Ricky Putra Globalindo Tbk",
  "CGAS": "PT Citra Nusantara Gemilang Tbk.",
  "SUPR": "Solusi Tunas Pratama Tbk",
  "TELE": "PT Omni Inovasi Indonesia Tbk",
  "NUSA": "PT Sinergi Megah Internusa Tbk",
  "NPGF": "PT Nusa Palapa Gemilang Tbk",
  "SOCI": "PT Soechi Lines Tbk.",
  "HUMI": "PT Humpuss Maritim Internasional Tbk",
  "PCAR": "PT Prima Cakrawala Abadi Tbk",
  "MKAP": "PT Multikarya Asia Pasifik Raya Tbk",
  "KOKA": "PT Koka Indonesia Tbk.",
  "LPLI": "Star Pacific Tbk",
  "CNKO": "Exploitasi Energi Indonesia Tbk",
  "GTSI": "PT GTS Internasional Tbk",
  "AREA": "PT Dunia Virtual Online Tbk",
  "BBRM": "Pelayaran Nasional Bina Buana Raya Tbk",
  "FITT": "PT Hotel Fitra International Tbk",
  "FOOD": "PT Sentra Food Indonesia Tbk.",
  "SKYB": "PT Northcliff Citranusa Indonesia Tbk.",
  "ETWA": "Eterindo Wahanatama Tbk",
  "CMPP": "PT AirAsia Indonesia Tbk",
  "NRCA": "PT Nusa Raya Cipta Tbk.",
  "LOPI": "PT Logisticsplus International Tbk",
  "WMPP": "PT Widodo Makmur Perkasa Tbk",
  "ATAP": "PT Trimitra Prawara Goldland Tbk",
  "PICO": "Pelangi Indah Canindo Tbk",
  "OKAS": "Ancora Indonesia Resources Tbk",
  "ACST": "PT Acset Indonusa Tbk.",
  "IDPR": "PT Indonesia Pondasi Raya Tbk.",
  "RDTX": "Roda Vivatex Tbk",
  "MTPS": "PT Meta Epsi Tbk.",
  "MTSM": "Metro Realty Tbk",
  "INAF": "Indofarma Tbk.",
  "KSIX": "PT Kentanix Supra International Tbk",
  "HOMI": "PT Grand House Mulia Tbk",
  "NIKL": "Pelat Timah Nusantara Tbk",
  "PNGO": "PT AEP Pinago Plantations Tbk",
  "TOPS": "PT Totalindo Eka Persada Tbk.",
  "MKNT": "PT Mitra Komunikasi Nusantara Tbk.",
  "BIMA": "Primarindo Asia Infrastructure Tbk",
  "HKMU": "PT HK Metals Utama Tbk",
}
