-- Orphan views: unreachable from the app, the ETL, or any other view.
-- Generated by scratchpad/deps.mjs against the DDL exported to sql/views_*.sql.
--
-- REVERSIBLE: every definition is preserved in sql/views_market.sql, views_main.sql,
-- and views_ksei.sql — re-run those CREATE VIEW statements to restore any of these.
--
-- Run in the MotherDuck UI. No CASCADE: if DuckDB reports a dependency, that view
-- is genuinely still in use — stop and re-check rather than forcing it.
DROP VIEW IF EXISTS ksei.vw_c_ksei_ownership_change;
DROP VIEW IF EXISTS ksei.vw_d_deepdive_ksei;
DROP VIEW IF EXISTS ksei.vw_f_ksei_investor_breakdown;
DROP VIEW IF EXISTS ksei.vw_group_ownership;
DROP VIEW IF EXISTS ksei.vw_ksei_monthly_stock_trend;
DROP VIEW IF EXISTS ksei.vw_monthly_aggregate;
DROP VIEW IF EXISTS ksei.vw_ownership_latest;
DROP VIEW IF EXISTS ksei.vw_s_ksei_concentration;
DROP VIEW IF EXISTS ksei.vw_s_ksei_foreign_breakdown;
DROP VIEW IF EXISTS ksei.vw_s_ksei_retail_distribution;
DROP VIEW IF EXISTS ksei.vw_smart_money;
DROP VIEW IF EXISTS main.vw_broker_consistency;
DROP VIEW IF EXISTS main.vw_broker_favorite_stocks;
DROP VIEW IF EXISTS main.vw_broker_stock_net;
DROP VIEW IF EXISTS main.vw_broker_summary;
DROP VIEW IF EXISTS main.vw_c_insider_score;
DROP VIEW IF EXISTS main.vw_d_deepdive_insider;
DROP VIEW IF EXISTS main.vw_d_insider_tab;
DROP VIEW IF EXISTS main.vw_f_broker_net_rolling;
DROP VIEW IF EXISTS main.vw_s_insider_buying;
DROP VIEW IF EXISTS main.vw_s_insider_cluster;
DROP VIEW IF EXISTS main.vw_s_insider_vs_price;
DROP VIEW IF EXISTS market.vw_a_conviction_screener_alert;
DROP VIEW IF EXISTS market.vw_a_daily_top_picks;
DROP VIEW IF EXISTS market.vw_a_market_regime_change;
DROP VIEW IF EXISTS market.vw_a_prime_broker_lead;
DROP VIEW IF EXISTS market.vw_a_score_breakout;
DROP VIEW IF EXISTS market.vw_a_sector_rotation_alert;
DROP VIEW IF EXISTS market.vw_a_volume_spike_alert;
DROP VIEW IF EXISTS market.vw_a_watchlist_alert;
DROP VIEW IF EXISTS market.vw_c_broker_score;
DROP VIEW IF EXISTS market.vw_c_composite_tier_pct;
DROP VIEW IF EXISTS market.vw_c_conviction_screener;
DROP VIEW IF EXISTS market.vw_c_daily_screener;
DROP VIEW IF EXISTS market.vw_c_distribution_warning;
DROP VIEW IF EXISTS market.vw_c_foreign_rotation;
DROP VIEW IF EXISTS market.vw_c_foreign_score;
DROP VIEW IF EXISTS market.vw_c_group_composite;
DROP VIEW IF EXISTS market.vw_c_insider_watchlist;
DROP VIEW IF EXISTS market.vw_c_price_score;
DROP VIEW IF EXISTS market.vw_c_sector_composite;
DROP VIEW IF EXISTS market.vw_c_whale_score;
DROP VIEW IF EXISTS market.vw_d_breadth_history;
DROP VIEW IF EXISTS market.vw_d_broker_intel_tab;
DROP VIEW IF EXISTS market.vw_d_deepdive_broker;
DROP VIEW IF EXISTS market.vw_d_deepdive_price;
DROP VIEW IF EXISTS market.vw_d_deepdive_summary;
DROP VIEW IF EXISTS market.vw_d_foreign_flow_history;
DROP VIEW IF EXISTS market.vw_d_group_momentum_tab;
DROP VIEW IF EXISTS market.vw_d_screener_tab;
DROP VIEW IF EXISTS market.vw_d_sector_rotation_tab;
DROP VIEW IF EXISTS market.vw_d_top_broker_net;
DROP VIEW IF EXISTS market.vw_d_watchlist_context;
DROP VIEW IF EXISTS market.vw_f_group_daily;
DROP VIEW IF EXISTS market.vw_f_sector_daily;
DROP VIEW IF EXISTS market.vw_s_breakout_technical;
DROP VIEW IF EXISTS market.vw_s_broker_accumulation;
DROP VIEW IF EXISTS market.vw_s_broker_convergence;
DROP VIEW IF EXISTS market.vw_s_broker_distribution;
DROP VIEW IF EXISTS market.vw_s_foreign_divergence;
DROP VIEW IF EXISTS market.vw_s_foreign_sector_rotation;
DROP VIEW IF EXISTS market.vw_s_group_momentum;
DROP VIEW IF EXISTS market.vw_s_price_momentum;
DROP VIEW IF EXISTS market.vw_s_price_vs_vwma;
DROP VIEW IF EXISTS market.vw_s_prime_broker_flow;
DROP VIEW IF EXISTS market.vw_s_sector_leadership;
DROP VIEW IF EXISTS market.vw_s_volume_spike;
DROP VIEW IF EXISTS market.vw_volume_spike;
